//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexNet.WebServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HDEL_PP_GET_ZPPR005Inputs", Namespace="http://schemas.datacontract.org/2004/07/FlexNet.WebServices")]
    public partial class HDEL_PP_GET_ZPPR005Inputs : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AUFNRField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUFNR
        {
            get
            {
                return this.AUFNRField;
            }
            set
            {
                this.AUFNRField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationInvocationResult", Namespace="http://schemas.datacontract.org/2004/07/FlexNet.WebServices")]
    public partial class OperationInvocationResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorField;
        
        private bool IsSuccessField;
        
        private int[] Output_CHNUMField;
        
        private int[] Output_SEQField;
        
        private string[] Output_TEXTField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Output_CHNUM
        {
            get
            {
                return this.Output_CHNUMField;
            }
            set
            {
                this.Output_CHNUMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Output_SEQ
        {
            get
            {
                return this.Output_SEQField;
            }
            set
            {
                this.Output_SEQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Output_TEXT
        {
            get
            {
                return this.Output_TEXTField;
            }
            set
            {
                this.Output_TEXTField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.apriso.com/DELMIAApriso", ConfigurationName="HDEL_PP_GET_ZPPR005")]
public interface HDEL_PP_GET_ZPPR005
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/Invoke", ReplyAction="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/InvokeResponse")]
    FlexNet.WebServices.OperationInvocationResult Invoke(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/Invoke", ReplyAction="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/InvokeResponse")]
    System.Threading.Tasks.Task<FlexNet.WebServices.OperationInvocationResult> InvokeAsync(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/Invoke_Async", ReplyAction="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/Invoke_AsyncResponse")]
    FlexNet.WebServices.OperationInvocationResult Invoke_Async(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/Invoke_Async", ReplyAction="http://www.apriso.com/DELMIAApriso/HDEL_PP_GET_ZPPR005/Invoke_AsyncResponse")]
    System.Threading.Tasks.Task<FlexNet.WebServices.OperationInvocationResult> Invoke_AsyncAsync(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface HDEL_PP_GET_ZPPR005Channel : HDEL_PP_GET_ZPPR005, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HDEL_PP_GET_ZPPR005Client : System.ServiceModel.ClientBase<HDEL_PP_GET_ZPPR005>, HDEL_PP_GET_ZPPR005
{
    
    public HDEL_PP_GET_ZPPR005Client()
    {
    }
    
    public HDEL_PP_GET_ZPPR005Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HDEL_PP_GET_ZPPR005Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HDEL_PP_GET_ZPPR005Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HDEL_PP_GET_ZPPR005Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FlexNet.WebServices.OperationInvocationResult Invoke(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs)
    {
        return base.Channel.Invoke(inputs);
    }
    
    public System.Threading.Tasks.Task<FlexNet.WebServices.OperationInvocationResult> InvokeAsync(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs)
    {
        return base.Channel.InvokeAsync(inputs);
    }
    
    public FlexNet.WebServices.OperationInvocationResult Invoke_Async(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs)
    {
        return base.Channel.Invoke_Async(inputs);
    }
    
    public System.Threading.Tasks.Task<FlexNet.WebServices.OperationInvocationResult> Invoke_AsyncAsync(FlexNet.WebServices.HDEL_PP_GET_ZPPR005Inputs inputs)
    {
        return base.Channel.Invoke_AsyncAsync(inputs);
    }
}
